- hosts: all
  tasks:
  - name: Install chocolatey/powershell on new systems
    win_chocolatey:
      name: powershell
      state: present
      execution_timeout: 0
    tags: powershell

  - name: Install extra software
    win_chocolatey:
      name:
      - 7zip
      - audacity
      - chocolateygui
      - firefox
      - gimp
      - googlechrome
      - infrarecorder
      - inkscape
      - keepass.install
      - libreoffice-oldstable
      - notepadplusplus
      - sysinternals
      - tigervnc
      - tipp10
      - vlc
      - windirstat
      - adblockplus-firefox
      - adblockplusie
      - adblockpluschrome
      state: present
      execution_timeout: 0
    tags: software
    ignore_errors: yes

  - name: Remove Google Drive File Stream
    win_chocolatey:
      name: google-drive-file-stream
      state: absent
      execution_timeout: 0
      ignore_checksums: yes
      force: yes
    ignore_errors: yes
    tags: gdrive

- hosts: dropbox
  tasks:
  - name: Install dropbox
    win_chocolatey:
      name: dropbox
      state: latest
      execution_timeout: 0
  tags: dropbox

- hosts: adobe
  tasks:
  - name: Install Adobe Acrobat Reader
    win_chocolatey:
      name: adobereader-update
      state: latest
      execution_timeout: 0
  tags: acrobat
